name: On Push Run2

on: push

env:
  DEVOPS_DIR: work

jobs:
  scrpy:
    name: scrp
    runs-on: ubuntu-latest
    steps:
    - name: Check-out work repository
      uses: actions/checkout@v2
      with:
        repository: jwebwatchdog/work
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.DEVOPS_DIR }}

    - name: scrp
      run: python ${{ env.DEVOPS_DIR }}/scrp.py
      shell: sh
#
